name: CI-CD Pipeline

on:
  push:
    branches:
      - deploytesting
      - main
      - testcicd
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      # Step 1: Checkout code
      - name: Checkout code
        uses: actions/checkout@v4

      # Step 2: Set up Go environment
      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: "1.24.1"

      # Step 3: Install Go dependencies
      - name: Install dependencies
        run: go mod download

      # Step 4: Run Go vet to check for code issues
      - name: Run go vet
        run: go vet ./...

      # Step 5: Build the Go binary
      - name: Build binary
        run: go build -o problemchallengeservice ./cmd

      # Step 6: Log in to Docker Hub
      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      # Step 7: Build and push Docker image
      - name: Build and push Docker image
        run: |
          docker build -t lijuthomas/problemchallengeservice:${{ github.sha }} -t lijuthomas/problemchallengeservice:latest .
          docker push lijuthomas/problemchallengeservice:${{ github.sha }}
          docker push lijuthomas/problemchallengeservice:latest

      # Step 8: Deploy to EC2
      - name: Deploy to EC2
        env:
          EC2_HOST: ${{ secrets.EC2_SERVER_IP }}
          SSH_KEY: ${{ secrets.EC2_SSH_KEY }}
        run: |
          echo "$SSH_KEY" > ssh_key.pem
          chmod 600 ssh_key.pem
          ssh -o StrictHostKeyChecking=no -i ssh_key.pem ubuntu@$EC2_HOST << EOF
            # Log in to Docker Hub on EC2
            echo "$DOCKERHUB_TOKEN" | docker login -u "$DOCKERHUB_USERNAME" --password-stdin

            # Stop and remove any existing container
            docker stop problemchallengeservice || true
            docker rm problemchallengeservice || true

            # Pull the latest Docker image
            docker pull lijuthomas/problemchallengeservice:latest

            # Run the Docker container with dynamically mapped .env file
            docker run -d --name problemchallengeservice -p 50055:50055 \
              -v $(pwd)/.env:/app/.env \
              lijuthomas/problemchallengeservice:latest

            #Log
            docker logs problemchallengeservice
          EOF
