name: CI-CD Pipeline

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.24.1'

      - name: Install dependencies
        run: go mod download

      - name: Run go vet
        run: go vet ./...

      - name: Build binary
        run: go build -o problemschallengeservice ./cmd

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push Docker image
        run: |
          docker build -t lijuthomas/problemschallengeservice:${{ github.sha }} -t lijuthomas/problemschallengeservice:latest .
          docker push lijuthomas/problemschallengeservice:${{ github.sha }}
          docker push lijuthomas/problemschallengeservice:latest

      - name: Deploy to EC2
        env:
          EC2_HOST: ${{ secrets.EC2_SERVER_IP }}
          SSH_KEY: ${{ secrets.EC2_SSH_KEY }}
          DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
          DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}
        run: |
          echo "$SSH_KEY" > ssh_key.pem
          chmod 600 ssh_key.pem
          ssh -o StrictHostKeyChecking=no -i ssh_key.pem ubuntu@$EC2_HOST << EOF
            echo "$DOCKERHUB_TOKEN" | docker login -u "$DOCKERHUB_USERNAME" --password-stdin
            docker stop problemschallengeservice || true
            docker rm problemschallengeservice || true
            docker pull lijuthomas/problemschallengeservice:latest
            docker run -d --name problemschallengeservice -p 50055:50055 \
              -e MONGODB_URL=mongodb://user:password@localhost:27017/problemsdb \
              -e PROBLEMCHALLENGE_REDIS_URL=redis://localhost:6379 \
              -e PROBLEMCHALLENGE_NATS_URL=nats://localhost:4222 \
              lijuthomas/problemschallengeservice:latest
          EOF